name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Mac OS Test
      run: xcodebuild clean build test -project DSValidator.xcodeproj -scheme "DSValidator" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=macOS'
    - name: IOS Simulator Test
      run: xcodebuild clean build test -project DSValidator.xcodeproj -scheme "DSValidator" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.2'
